[package]
name = "newoverlay"
version = "0.1.0"
edition = "2021"

[lib]
name = "newoverlay"
path = "src/lib.rs"

[dependencies]
wry = { version = "0.54", features = ["transparent"] }
raw-window-handle = "0.6"

[dependencies.winapi]
version = "0.3"
features = [
    "winuser",
    "windef",
    "libloaderapi",
]
